(define (double n)
  (* n 2))
(define (halve n)
  (/ n 2))
(define (even? n)
  (= (remainder n 2) 0))
(define (fast-mul a b)
  (display a) (display ", ") (display b) (newline)
  (cond ((= b 0) 0)
        ((even? b) (double (fast-mul a (halve b))))
        (else (+ a (fast-mul a (+ b -1))))))

(fast-mul 8 10)